import logging
from io import BytesIO
from fpdf import FPDF

logger = logging.getLogger("pdf_generator")


def generate_intake_pdf(lawyer: dict, intake: dict) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"{lawyer['firm_name']}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Attorney: {lawyer['lawyer_name']}", new_x="LMARGIN", new_y="NEXT", align="C")
    if lawyer.get("email"):
        pdf.cell(0, 7, lawyer["email"], new_x="LMARGIN", new_y="NEXT", align="C")
    if lawyer.get("phone"):
        pdf.cell(0, 7, lawyer["phone"], new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.ln(5)
    pdf.set_draw_color(0, 82, 136)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # Title
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Client Intake Form - Completed", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(3)

    # Submitted date
    if intake.get("submitted_at"):
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, f"Submitted: {intake['submitted_at'][:10]}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(5)

    # Personal Information Section
    _section_header(pdf, "Personal Information")
    _field_row(pdf, "Full Name", intake.get("full_name", ""))
    _field_row(pdf, "Maiden Name", intake.get("maiden_name", ""))
    _field_row(pdf, "Date of Birth", intake.get("birth_date", ""))
    _field_row(pdf, "City/State Where Born", intake.get("city_state_born", ""))
    _field_row(pdf, "Driver's License (Last 3)", intake.get("drivers_license_last3", ""))
    _field_row(pdf, "SSN (Last 3)", intake.get("ssn_last3", ""))

    # Contact Information Section
    _section_header(pdf, "Contact Information")
    _field_row(pdf, "Address", intake.get("address", ""))
    _field_row(pdf, "City", intake.get("city", ""))
    _field_row(pdf, "County", intake.get("county", ""))
    _field_row(pdf, "State", intake.get("state", ""))
    _field_row(pdf, "Zip", intake.get("zip", ""))
    _field_row(pdf, "Phone", intake.get("phone", ""))
    _field_row(pdf, "Email", intake.get("email", ""))

    # Employment Information Section
    _section_header(pdf, "Employment Information")
    _field_row(pdf, "Employer", intake.get("employer", ""))
    _field_row(pdf, "Job Title", intake.get("job_title", ""))
    _field_row(pdf, "Employer Address", intake.get("employer_address", ""))
    _field_row(pdf, "Employer City/State/Zip", intake.get("employer_city_state_zip", ""))
    _field_row(pdf, "Gross Salary", intake.get("gross_salary", ""))
    _field_row(pdf, "Length of Employment", intake.get("length_of_employment", ""))
    _field_row(pdf, "Education", intake.get("education", ""))

    # Footer
    pdf.ln(10)
    pdf.set_draw_color(0, 82, 136)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by OurFamilyWizard Pro - Parenting Plan Builder", new_x="LMARGIN", new_y="NEXT", align="C")

    return pdf.output()


def _section_header(pdf: FPDF, title: str):
    pdf.ln(3)
    pdf.set_fill_color(0, 82, 136)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, f"  {title}", new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)


def _field_row(pdf: FPDF, label: str, value: str):
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(55, 7, f"{label}:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, value or "N/A", new_x="LMARGIN", new_y="NEXT")
